name: Papito CI/CD
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  IMAGE: aviorp/node-ts-server
  USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  PASSWORD: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node Environment
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install NPM Packages
        run: npm ci

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Build 
        run: npm run build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: dist
  Tests:
    needs: [Setup]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-output
          path: dist

      - name: Restore cache
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Deploy Check
        run: npm run deploy-check

  Image-Update:
    if : ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    needs: [Setup, Tests]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Restore cache
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-output
          path: dist

      - name: Build & Push Image
        run: npm run docker
